import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const t = fs.readFileSync(path.join(root, "src/lib/i18n/uiStrings.ts"), "utf8");
const s = t.indexOf("const ES: UiMessages = {");
const e = t.indexOf("\n};\n\nconst DE:", s);
const chunk = t.slice(s, e);
const keys = [...chunk.matchAll(/\n\s+"([^"]+)":/g)].map((m) => m[1]);

/** Greek UI for keys that ES overrides (same order as appearance). */
const el = {
  "nav.reports": "Αναφορές",
  "nav.signOut": "Αποσύνδεση",
  "nav.dashboard": "Πίνακας ελέγχου",
  "nav.allSchools": "Όλα τα σχολεία",
  "nav.classesLanguage": "Τάξεις και γλώσσα",
  "nav.class": "Τάξη",
  "nav.backDashboard": "← Πίνακας ελέγχου",
  "a11y.uiLanguage": "Γλώσσα περιβάλλοντος",
  "dash.title": "Πίνακας ελέγχου",
  "dash.signedInAs": "Σύνδεση ως",
  "dash.sessionEnds": "Η συνεδρία λήγει",
  "dash.left": "απομένουν",
  "dash.lessThanHour": "λιγότερο από μία ώρα",
  "dash.aboutOneHour": "περίπου 1 ώρα",
  "dash.aboutHours": "περίπου {n} ώρες",
  "dash.loadOrgsError": "Δεν ήταν δυνατή η φόρτωση οργανισμών",
  "dash.noSchoolTitle": "Κανένα σχολείο δεν έχει συνδεθεί ακόμη",
  "dash.noSchoolBody":
    "Δημιουργήστε λογαριασμό από τη σελίδα υποδοχής ή ζητήστε από υπεύθυνο να προσθέσει το email σας.",
  "dash.ownerBlurbTitle": "Χώρος εργασίας ιδιοκτήτη λογαριασμού",
  "dash.ownerBlurbBody":
    "Προσκαλείτε ομάδα, ορίζετε γλώσσα αναφορών, δημιουργείτε τάξεις, αναθέτετε εκπαιδευτικούς και ανοίγετε όλες τις αναφορές.",
  "dash.dhBlurbTitle": "Χώρος υπεύθυνου τμήματος",
  "dash.dhBlurbBody": "Προσκαλείτε εκπαιδευτικούς, ορίζετε γλώσσα, δημιουργείτε τάξεις και αναθέσεις.",
  "dash.teacherBlurbTitle": "Χώρος εκπαιδευτικού",
  "dash.teacherBlurbBody": "Χρησιμοποιήστε τις Αναφορές για να ανοίξετε σχολείο· βλέπετε μόνο τις ανατεθειμένες τάξεις.",
  "dash.yourSchools": "Τα σχολεία σας",
  "dash.yourSchoolsHint": "Ρόλος και ενέργειες ανά οργανισμό.",
  "dash.schoolFocusTitle": "Επιλέξτε σχολείο",
  "dash.schoolFocusHint":
    "Επιλέξτε σχολείο για να ανοίξετε τον χώρο εργασίας παρακάτω.",
  "dash.schoolWorkspaceMenuTitle": "Χώρος σχολείου",
  "dash.schoolWorkspaceMenuHint": "Επεξεργαστείτε το σχολείο που επιλέξατε παραπάνω.",
  "dash.panelOverview": "Επισκόπηση",
  "dash.panelPdfLetterhead": "Κεφαλίδα PDF",
  "dash.panelInviteTeam": "Πρόσκληση ομάδας",
  "dash.clearSchoolSelection": "Καθαρισμός επιλογής σχολείου",
  "dash.beAnAgent": "Γίνετε πράκτορας",
  "dash.agentCardClose": "Κλείσιμο",
  "dash.role.owner": "Ιδιοκτήτης",
  "dash.role.department_head": "Υπεύθυνος τμήματος",
  "dash.role.teacher": "Εκπαιδευτικός",
  "dash.roleDesc.owner":
    "Πλήρης έλεγχος: προσκλήσεις, γλώσσα σχολείου, όλες οι τάξεις και αναφορές, ανάθεση εκπαιδευτικών.",
  "dash.roleDesc.department_head":
    "Πρόσκληση εκπαιδευτικών, γλώσσα σχολείου, όλες οι τάξεις και αναφορές, αναθέσεις.",
  "dash.roleDesc.teacher": "Τάξεις και αναφορές όπου είστε ανατεθειμένος.",
  "dash.reportsClasses": "Αναφορές και τάξεις",
  "dash.teamRoster": "Ομάδα",
  "dash.inviteTeam": "Πρόσκληση ομάδας",
  "dash.inviteTeamHint":
    "Οι υπεύθυνοι τμήματος προσθέτουν εκπαιδευτικούς. Σύνδεση με το προσκεκλημένο email και κωδικό μίας χρήσης.",
  "dash.addSchoolTitle": "Προσθήκη άλλου σχολείου",
  "dash.addSchoolHint": "Δημιουργήστε επιπλέον οργανισμό του οποίου θα είστε ιδιοκτήτης.",
  "dash.addSchoolPlaceholder": "Όνομα σχολείου",
  "dash.addSchoolButton": "Προσθήκη σχολείου",
  "dash.addSchoolWorking": "Γίνεται προσθήκη…",
  "dash.pdfLetterheadTitle": "Κεφαλίδα PDF (ιδιοκτήτης)",
  "dash.pdfLetterheadHint":
    "Λογότυπο αριστερά, υπότιτλος κάτω. PNG, JPEG ή WebP (~3∶1 ±10 %, έως 4 MB). Αποθηκεύστε και προεπισκοπήστε.",
  "dash.pdfLetterheadName": "Επίσημο όνομα στο PDF (προαιρετικό)",
  "dash.pdfLetterheadTagline": "Υπότιτλος (προαιρετικό, κάτω από το λογότυπο)",
  "dash.pdfLetterheadAddress": "Διεύθυνση (προαιρετικό, πολλές γραμμές)",
  "dash.pdfLetterheadContact": "Επικοινωνία (τηλ., email, ιστότοπος)",
  "dash.pdfLetterheadLogo": "Λογότυπο σχολείου",
  "dash.pdfLetterheadLogoPick": "Επιλογή εικόνας…",
  "dash.pdfLetterheadLogoUploading": "Μεταφόρτωση…",
  "dash.pdfLetterheadLogoRemove": "Αφαίρεση λογότυπου",
  "dash.pdfLetterheadLogoHint": "PNG, JPEG ή WebP. Οριζόντια ~3∶1 (±10%). Έως 4 MB· βελτιστοποιημένο για εκτύπωση.",
  "dash.pdfLetterheadSave": "Αποθήκευση κεφαλίδας",
  "dash.pdfLetterheadSaving": "Αποθήκευση…",
  "dash.pdfLetterheadPreview": "Προεπισκόπηση δείγματος PDF",
  "dash.pdfPreviewTitle": "Προεπισκόπηση PDF",
  "dash.pdfPreviewClose": "Κλείσιμο",
  "report.pdfPreview": "Προεπισκόπηση PDF",
  "report.pdfPreviewHint":
    "Ανοίγει το PDF όπως αποθηκεύτηκε τελευταία στο διακομιστή. Αποθηκεύστε την αναφορά αν έχετε μη αποθηκευμένες αλλαγές.",
  "report.pdfPreviewClose": "Κλείσιμο προεπισκόπησης",
  "reports.title": "Αναφορές",
  "reports.hint": "Επιλέξτε σχολείο για προσθήκη μαθητών και σύνταξη αναφορών.",
  "reports.notLinked": "Δεν είστε συνδεδεμένοι με κανένα σχολείο ακόμη.",
  "reports.loadError": "Δεν ήταν δυνατή η φόρτωση σχολείων.",
  "tenant.ownerBannerTitle": "Ιδιοκτήτης — πλήρης έλεγχος",
  "tenant.ownerBannerBody":
    "Ορίζετε τη γλώσσα αναφορών, δημιουργείτε τάξεις, προσκαλείτε ομάδα, αναθέτετε εκπαιδευτικούς και έχετε πρόσβαση σε όλα στο {school}.",
  "tenant.dhBannerTitle": "Υπεύθυνος τμήματος",
  "tenant.dhBannerBody":
    "Προσκαλείτε εκπαιδευτικούς, δημιουργείτε τάξεις, αναθέτετε εκπαιδευτικό και εργάζεστε σε όλες τις αναφορές στο {school}.",
  "tenant.teacherBannerTitle": "Εκπαιδευτικός — ανατεθειμένες τάξεις",
  "tenant.teacherBannerBody":
    "Βλέπετε μόνο τάξεις με το email σας. Ανοίξτε τάξη για μαθητές και αναφορές.",
  "tenant.introLead":
    "Ορίστε την προεπιλεγμένη γλώσσα αναφορών για το {school}. Δημιουργήστε τάξη και ανοίξτε την για ανάθεση εκπαιδευτικού και μαθητές.",
  "tenant.introTeacher": "Η γλώσσα ορίζεται από υπεύθυνο. Ανοίξτε ανατεθειμένη τάξη παρακάτω.",
  "tenant.schoolLangTitle": "Προεπιλεγμένη γλώσσα αναφορών σχολείου",
  "tenant.schoolLangLead": "Ισχύει για νέες αναφορές· η τάξη ή η αναφορά μπορεί να την αλλάξει.",
  "tenant.schoolLangReadonly": "Μόνο ανάγνωση — την αλλάζουν οι υπεύθυνοι.",
  "tenant.saving": "Αποθήκευση…",
  "tenant.bulkDownloadsTitle": "Μαζικές λήψεις",
  "tenant.bulkDownloadsLead": "Κατεβάστε πολλές αναφορές σε ένα συνδυασμένο PDF για γρηγορότερη εκτύπωση.",
  "tenant.bulkTeacherLabel": "Εκπαιδευτικός",
  "tenant.bulkGroupByLabel": "Ομαδοποίηση κατά",
  "tenant.bulkGroupTerm": "Περίοδος",
  "tenant.bulkGroupTeacher": "Εκπαιδευτικός",
  "tenant.bulkGroupClass": "Τάξη",
  "tenant.bulkGroupStudent": "Μαθητής",
  "tenant.finalOnly": "Ολοκληρωμένες αναφορές",
  "tenant.downloadTeacherPdfsOneFile": "Λήψη PDF εκπαιδευτικού (ένα αρχείο)",
  "tenant.downloadBulkPdfsOneFile": "Λήψη συνδυασμένου PDF (ένα αρχείο)",
  "tenant.newClassPlaceholder": "π.χ. Α1",
  "tenant.classesTitle": "Τάξεις",
  "tenant.newClassName": "Όνομα νέας τάξης",
  "tenant.createClass": "Δημιουργία τάξης",
  "tenant.onlyLeadsCreate": "Μόνο ιδιοκτήτες και υπεύθυνοι μπορούν να δημιουργούν τάξεις.",
  "tenant.openClass": "Άνοιγμα τάξης",
  "tenant.delete": "Διαγραφή",
  "tenant.pupil": "μαθητής",
  "tenant.pupils": "μαθητές",
  "tenant.noClassesLead": "Καμία τάξη ακόμη — δημιουργήστε μία παραπάνω.",
  "tenant.noClassesTeacher": "Καμία ανατεθειμένη τάξη. Υπεύθυνος πρέπει να συνδέσει το email σας.",
  "tenant.sectionMenuTitle": "Εμφάνιση ενοτήτων",
  "tenant.sectionMenuHint":
    "Τίποτα δεν εμφανίζεται μέχρι να ενεργοποιήσετε ενότητα. Κλικ για εμφάνιση· ξανά για απόκρυψη.",
  "tenant.panelWelcome": "Καλώς ήρθατε και συμβουλές",
  "tenant.panelTimetable": "Ωρολόγιο",
  "tenant.panelLanguage": "Γλώσσα αναφορών",
  "tenant.panelBulk": "Μαζικές λήψεις",
  "tenant.panelDownloads": "Λήψεις",
  "tenant.panelClasses": "Τάξεις",
  "tenant.confirmDeleteClass": "Διαγραφή τάξης «{name}» και όλων των μαθητών και αναφορών;",
  "class.studentsHint":
    "Επιλογή τριμήνου, πλέγμα 0–10 και ΣΥΝ στην αναφορά κάθε μαθητή (όχι εδώ).",
  "class.bulkPdfWhichReports": "Η μαζική λήψη περιλαμβάνει",
  "class.bulkPdfAllReady": "Όλες οι έτοιμες αναφορές",
  "class.groupDownloadBy": "Ομαδοποίηση λήψης κατά",
  "class.groupDownloadThisClass": "Αυτή η τάξη",
  "class.panelBulkDownload": "Μαζική λήψη",
  "class.panelMovePupil": "Μετακίνηση μαθητή",
  "class.bulkDownloadTermLabel": "Τρίμηνο",
  "class.bulkDownloadSelectLabel": "Επιλέξτε",
  "class.bulkDownloadPanelHint":
    "Μόνο αυτή η τάξη: ένα PDF με την ολοκληρωμένη αναφορά κάθε μαθητή για το επιλεγμένο τρίμηνο (1, 2 ή 3).",
  "archive.title": "Αρχεία σχολικού έτους",
  "archive.emptyExpl":
    "Όταν αλλάζει το σχολικό έτος, οι αναφορές του προηγούμενου αποθηκεύονται εδώ. Οι μαθητές παραμένουν· οι αναφορές ξεκινούν από την αρχή.",
  "archive.none": "Κανένα αρχείο ακόμη.",
  "archive.readonlyExpl":
    "Στιγμιότυπα μόνο ανάγνωσης. Η αλλαγή έτους αρχειοθετεί το προηγούμενο και καθαρίζει τις τρέχουσες αναφορές.",
  "archive.archived": "Αρχειοθετημένο",
  "archive.review": "Ανασκόπηση",
  "archive.loading": "Φόρτωση…",
  "archive.close": "Κλείσιμο",
  "archive.noPupils": "Κανένας μαθητής σε αυτό το στιγμιότυπο.",
  "archive.noReports": "Καμία αναφορά.",
  "archive.reportN": "Αποθηκευμένη αναφορά {n}",
  "archive.termFocus": "Τρίμηνο αναφοράς",
  "archive.termFocusShortCourse": "Αναφορά σύντομου κύκλου (μία περίοδος)",
  "archive.gradesTitleShortCourse": "Βαθμοί (0–10) — σύντομος κύκλος",
  "archive.term1": "Τρίμηνο 1",
  "archive.term2": "Τρίμηνο 2",
  "archive.term3": "Τρίμηνο 3",
  "archive.gradesTitle": "Βαθμοί (0–10) — όλα τα τρίμηνα",
  "archive.pdfComment": "Σχόλιο PDF / γονέων",
  "archive.teacherComment": "Προεπισκόπηση εκπαιδευτικού",
  "archive.updated": "Ενημερώθηκε",
  "report.contextTitle": "Πλαίσιο (από τάξη και σχολείο)",
  "report.className": "Όνομα τάξης",
  "report.scholasticYear": "Σχολικό έτος",
  "report.cefr": "Επίπεδο CEFR",
  "report.defaultSubject": "Προεπιλεγμένο μάθημα (τάξη)",
  "report.teacherSignedIn": "Εκπαιδευτικός (συνδεδεμένος)",
  "report.pdfLang": "Γλώσσα εξόδου PDF / γονέων",
  "report.pdfLangHint":
    "Κανονικό σχόλιο για γονείς και PDF. Αλλάξτε γλώσσα PDF και εκτελέστε ξανά τη ΣΥΝ.",
  "report.teacherPreviewLang": "Γλώσσα προεπισκόπησης εκπαιδευτικού",
  "report.teacherPreviewHint":
    "Μετάφραση του σχολίου γονέων. Η αλλαγή ξαναμεταφράζει το τρέχον κείμενο.",
  "report.subjectOverride": "Μάθημα (παράκαμψη)",
  "report.useClassDefault": "Χρήση προεπιλογής τάξης ({subject})",
  "report.studentTitle": "Μαθητής (για PDF· το επώνυμο δεν στέλνεται στη ΣΥΝ)",
  "report.firstName": "Όνομα(τα)",
  "report.lastName": "Επώνυμο(α)",
  "report.gender": "Ταυτότητα φύλου",
  "report.saveStudent": "Αποθήκευση στοιχείων μαθητή",
  "report.termGradesTitle": "Βαθμοί τριμήνου (0–10)",
  "report.termGradesHint":
    "Επιλέξτε τρίμηνο αναφοράς και συμπληρώστε βαθμούς. Η ΣΥΝ και το PDF χρησιμοποιούν το ίδιο τρίμηνο.",
  "report.termForReport": "Τρίμηνο αυτής της αναφοράς",
  "report.termFirst": "Πρώτο τρίμηνο",
  "report.termSecond": "Δεύτερο τρίμηνο",
  "report.termThird": "Τρίτο τρίμηνο",
  "report.termTotal": "Σύνολο τριμήνου (όλα τα 16 κελιά):",
  "report.termInputs": "— δεδομένα αναφοράς",
  "report.optionalNotes": "Προαιρετικές σημειώσεις (μόνο για ΣΥΝ)",
  "report.optionalNotesHint":
    "Δεν εμφανίζονται στο PDF. Αποθηκεύονται με την αναφορά και στέλνονται στη ΣΥΝ με τους βαθμούς.",
  "report.generatedTitle": "Δημιουργημένα σχόλια",
  "report.generatedHint":
    "Για {term}. Το PDF είναι κύριο· η προεπισκόπηση είναι μετάφραση. Η αφαίρεση καθαρίζει και τα δύο.",
  "report.runAi": "Εκτελέστε τη ΣΥΝ για δημιουργία σχολίου γονέων.",
  "report.teacherPreviewPlaceholder": "— Ίδιο με PDF αν το ίδιο, αλλιώς μεταφρασμένο.",
  "report.saveReport": "Αποθήκευση αναφοράς",
  "report.downloadPdf": "Λήψη PDF",
  "report.remove": "Αφαίρεση",
  "report.aiTitle": "Σχόλιο ΣΥΝ (σύνολο 0–10 Prompt A1)",
  "report.aiHint":
    "Απαιτεί OPENAI_API_KEY. Γράφει πρώτα το σχόλιο γονέων και το μεταφράζει στην προεπισκόπηση εκπαιδευτικού. Μόνο μικρό όνομα.",
  "report.aiFillHint": "Συμπληρώστε και τα 48 κελιά (0–10) για αξιόπιστο προσχέδιο.",
  "report.generateAi": "Δημιουργία σχολίων ΣΥΝ",
  "report.generating": "Δημιουργία…",
  "report.backClass": "← Επιστροφή στην τάξη",
  "report.pageTitle": "Ατομική αναφορά μαθητή",
  "report.pageIntro":
    "Τάξη, μάθημα και έτος ορίζονται στην οθόνη τάξης· αλλάξτε εδώ μόνο αν χρειάζεται.",
  "report.pageIntroShort":
    "Τελική αναφορά σύντομου κύκλου: ένα πλέγμα 0–10 και ένα σχόλιο. Τα τρίμηνα 2 και 3 δεν χρησιμοποιούνται.",
  "report.shortCourseBadge": "Αναφορά σύντομου κύκλου",
  "report.shortCourseGradesTitle": "Βαθμοί σύντομου κύκλου (0–10)",
  "report.shortCourseGradesHint":
    "Εισάγετε βαθμούς μόνο για τον σύντομο κύκλο. Η ΣΥΝ και το PDF χρησιμοποιούν αυτό το μπλοκ.",
  "report.shortCourseTermHeading": "Περίοδος σύντομου κύκλου",
  "report.generatedHintShort":
    "Σχόλιο τέλους σύντομου κύκλου. Το PDF είναι κύριο· η προεπισκόπηση είναι μετάφραση.",
  "report.aiFillHintShort": "Συμπληρώστε και τα 16 κελιά (0–10) για αξιόπιστο προσχέδιο.",
  "report.loading": "Φόρτωση…",
  "report.genderMale": "Άνδρας",
  "report.genderFemale": "Γυναίκα",
  "report.genderNonBinary": "Μη δυαδικό",
  "report.errorNamesRequired": "Απαιτούνται όνομα και επώνυμο.",
  "report.wrongClass": "Η αναφορά δεν ανήκει στην τάξη του URL.",
  "report.loadFailed": "Η φόρτωση απέτυχε",
  "report.confirmClearComments": "Να αφαιρεθούν και τα δύο δημιουργημένα σχόλια (PDF και προεπισκόπηση);",
  "report.errUpdateTeacherPreview": "Αποτυχία ενημέρωσης προεπισκόπησης",
  "report.errSaveBeforeAi": "Αποτυχία αποθήκευσης πριν από ΣΥΝ",
  "report.errAi": "Η ΣΥΝ απέτυχε",
  "pdf.gradesColDimension": "Διάσταση (0–10)",
  "pdf.gradesTerm1": "Τ1",
  "pdf.gradesTerm2": "Τ2",
  "pdf.gradesTerm3": "Τ3",
  "pdf.gradesShortCourseCol": "Σύντομος κύκλος",
  "pdf.gradesSectionTitle": "Ακαδημαϊκό ιστορικό (δομημένο)",
  "pdf.gradesSectionIntro": "Οι αριθμητικές κλίμακες είναι 0–10 σε τρία τρίμηνα.",
  "pdf.gradesSectionIntroShortCourse":
    "Βαθμοί 0–10 μόνο για αυτή την περίοδο σύντομου κύκλου (μία παρατήρηση).",
  "pdf.gradesTermAverage": "Μέσος {term}: {value}",
  "pdf.gradesShortCourseAverage": "Μέσος {term}: {value}",
  "pdf.gradesYearAverage": "Ετήσιος μέσος όρος: {value}",
  "pdf.shortCourseReportFocus": "Σύντομος κύκλος",
  "pdf.metaReportFocus": "Εστίαση αναφοράς",
  "pdf.defaultReportTitleSuffix": "Αναφορά",
  "pdf.studentLine": "Μαθητής: {name}",
  "pdf.metaClass": "Τάξη: {name}",
  "pdf.metaScholasticYear": "Σχολικό έτος: {year}",
  "pdf.metaCefr": "CEFR: {level}",
  "pdf.metaSubject": "Μάθημα: {subject}",
  "pdf.metaReportLanguage": "Γλώσσα αναφοράς: {label}",
  "pdf.emptyParentComment": "—",
  "pdf.generatedStamp": "Δημιουργήθηκε {datetime}",
  "pdf.sampleStudentName": "Δείγμα μαθητή",
  "pdf.sampleClassName": "Δείγμα τάξης",
  "pdf.sampleCommentBody":
    "Αυτή η παράγραφος δείχνει πώς εμφανίζεται το σχόλιο γονέων στη σελ. 2 του PDF. Η σελ. 1 έχει το ακαδημαϊκό ιστορικό.",
  "pdf.registerAbbr.mon": "Δε",
  "pdf.registerAbbr.tue": "Τρ",
  "pdf.registerAbbr.wed": "Τε",
  "pdf.registerAbbr.thu": "Πε",
  "pdf.registerAbbr.fri": "Πα",
  "pdf.registerAbbr.sat": "Σα",
  "pdf.registerAbbr.sun": "Κυ",
  "pdf.registerMonth": "Μήνας",
  "pdf.timetableTitle": "Εβδομαδιαίο ωρολόγιο",
  "pdf.timetableMyTitle": "Το ωρολόγιό μου",
  "pdf.timetableLunch": "Διάλειμμα φαγητού",
  "pdf.timetablePeriodAm": "ΠΜ {n}",
  "pdf.timetablePeriodPm": "ΜΜ {n}",
  "pdf.timetableRoomN": "Αίθ. {n}",
  "pdf.timetablePageRoom": "Αίθουσα {n}",
  "common.failed": "Αποτυχία",
  "common.genericError": "Κάτι πήγε στραβά.",
  "billing.title": "Αγορά πιστώσεων αναφορών",
  "billing.leadOwnerLine1": "Οι πιστώσεις προστίθενται στον",
  "billing.leadOwnerAccount": "λογαριασμό ιδιοκτήτη σας",
  "billing.leadOwnerLine2":
    "και τις μοιράζονται όλα τα σχολεία σας (συμπεριλαμβανομένου {school}). Η αγορά εδώ διατηρεί το ιστορικό Stripe με αυτό το σχολείο.",
  "billing.leadNonOwner": "Το {school} χρειάζεται πιστώσεις για να δημιουργείτε αναφορές.",
  "billing.currentBalanceLabel": "Τρέχον υπόλοιπο (αυτός ο λογαριασμός):",
  "billing.reportsRemaining": "{n} αναφορές απομένουν",
  "billing.ownerOnly": "Μόνο ιδιοκτήτες σχολείου μπορούν να αγοράσουν πιστώσεις.",
  "billing.continuePayment": "Συνέχεια στην πληρωμή",
  "billing.packLine": "{credits} αναφορές • Σύνολο: {price} {currency}",
  "billing.packTaxIncluded": "Η τιμή περιλαμβάνει ήδη {taxDetail}.",
  "billing.packTaxAddedToBase": "Προστίθεται {taxDetail}· το σύνολο παραπάνω είναι αυτό που πληρώνετε.",
  "billing.packNetBeforeTax": "Τιμή πακέτου πριν από {tax}: {price} {currency}",
  "billing.testTrialActive":
    "Δοκιμή sandbox: {n} δωρεάν δοκιμαστικές αναφορές σε αυτό το σχολείο.",
  "billing.testConvertLead":
    "Οι δωρεάν δοκιμές τελείωσαν. Αγοράστε πακέτο για πλήρη λογαριασμό (Stripe).",
  "billing.backReports": "Πίσω στις αναφορές",
  "billing.successTitle": "Η πληρωμή ελήφθη",
  "billing.successBody": "Ευχαριστούμε. Αν οι πιστώσεις δεν εμφανιστούν αμέσως, περιμένετε επιβεβαίωση Stripe.",
  "billing.continueToSchool": "Συνέχεια στο {school}",
  "billing.backBilling": "Πίσω στη χρέωση",
  "dash.tenantLangTitle": "Προεπιλεγμένη γλώσσα αναφορών (ανά σχολείο)",
  "dash.tenantLangHint":
    "Ισχύει για νέες τάξεις και αναφορές εκτός παράκαμψης. Οι υπεύθυνοι το αλλάζουν· οι εκπαιδευτικοί μόνο ανάγνωση.",
  "invite.headingOwner": "Πρόσκληση στο {school}",
  "invite.headingDh": "Πρόσκληση εκπαιδευτικών — {school}",
  "invite.descriptionOwner":
    "Προσθέστε υπεύθυνους ή εκπαιδευτικούς με email. Συνδέονται με την ίδια διεύθυνση (κωδικός μίας χρήσης).",
  "invite.descriptionDh": "Οι υπεύθυνοι προσθέτουν μόνο εκπαιδευτικούς. Ίδια ροή σύνδεσης.",
  "invite.email": "Email",
  "invite.emailPlaceholder": "συνάδελφος@σχολείο.edu",
  "invite.role": "Ρόλος",
  "invite.optionTeacher": "Εκπαιδευτικός",
  "invite.optionDeptHead": "Υπεύθυνος τμήματος",
  "invite.roleLine": "Ρόλος:",
  "invite.addMember": "Προσθήκη μέλους",
  "invite.addTeacher": "Προσθήκη εκπαιδευτικού",
  "invite.adding": "Προσθήκη…",
  "invite.okBase": "Η πρόσβαση προστέθηκε.",
  "invite.okEmailPart": " Θα λάβουν email πρόσκλησης με σύνδεσμο.",
  "invite.okSignInPart": " Πρέπει να συνδεθούν με το δικό τους email σχετικά με τον κωδικό.",
  "deleteSchool.prompt":
    "Διαγραφή σχολείου «{name}» και ΟΛΩΝ τάξεων, μαθητών και αναφορών; Πληκτρολογήστε DELETE για επιβεβαίωση.",
  "deleteSchool.confirmToken": "DELETE",
  "deleteSchool.button": "Διαγραφή σχολείου (μόνο ιδιοκτήτης)",
  "deleteSchool.deleting": "Διαγραφή…",
  "roster.thEmail": "Email",
  "roster.thRole": "Ρόλος",
  "roster.thActions": "Ενέργειες",
  "roster.remove": "Αφαίρεση",
  "roster.removing": "…",
  "roster.confirmRemove": "Αφαίρεση {email} από αυτό το σχολείο; Θα χάσει την πρόσβαση μέχρι νέα πρόσκληση.",
  "roster.roleDeptShort": "Υπ. τμ.",
  "class.intro":
    "Ορίστε όνομα τάξης, έτος, CEFR, μάθημα και προεπιλεγμένη γλώσσα εξόδου. Η σελίδα αναφοράς παρακάμπτει μόνο όταν χρειάζεται.",
  "class.introTeacher":
    "Οι προεπιλογές τάξης ορίζονται από ιδιοκτήτη ή υπεύθυνο. Μπορείτε να αλλάξετε γλώσσα εξόδου ανά αναφορά.",
  "class.settingsTitle": "Ρυθμίσεις τάξης",
  "class.tipLabel": "Συμβουλή",
  "class.nameTimetableTip":
    "Αν συμπεριλάβετε την ώρα έναρξης στο όνομα τάξης, θα εμφανίζεται στο ωρολόγιο.",
  "class.className": "Όνομα τάξης",
  "class.scholasticYear": "Σχολικό έτος (εεεε – εεεε)",
  "class.scholasticPlaceholder": "π.χ. 2024 – 2025",
  "class.yearReadonlyHint": "Μόνο ιδιοκτήτες και υπεύθυνοι αλλάζουν το σχολικό έτος.",
  "class.coreSettingsReadonlyHint":
    "Μόνο ιδιοκτήτης ή υπεύθυνος αλλάζει: όνομα, έτος, CEFR, προεπιλεγμένο μάθημα και γλώσσα, τύπο νέων αναφορών, ενεργές ημέρες.",
  "class.teacherPerReportOutputLangHint": "Μπορείτε ακόμη να ορίσετε γλώσσα εξόδου ανά αναφορά.",
  "class.cefr": "Επίπεδο τάξης (CEFR)",
  "class.defaultSubject": "Προεπιλεγμένο μάθημα",
  "class.defaultOutputLang": "Προεπιλεγμένη γλώσσα εξόδου",
  "class.teacherHeading": "Εκπαιδευτικός",
  "class.assignedTeacher": "Ανατεθειμένος εκπαιδευτικός (πρέπει να ταιριάζει με το προσκεκλημένο email)",
  "class.notAssigned": "— Δεν έχει ανατεθεί —",
  "class.currentSuffix": "(τρέχον)",
  "class.assignedTeacherHint": "Οι εκπαιδευτικοί βλέπουν μόνο ανατεθειμένες τάξεις. Προσκαλέστε από τον πίνακα.",
  "class.assignmentLabel": "Ανάθεση τάξης:",
  "class.saveSettings": "Αποθήκευση ρυθμίσεων",
  "class.deleteClass": "Διαγραφή τάξης",
  "class.studentsTitle": "Μαθητές σε αυτή την τάξη",
  "class.firstName": "Όνομα(τα)",
  "class.lastName": "Επώνυμο(α)",
  "class.genderOptional": "Φύλο (προαιρετικό)",
  "class.addPupil": "Προσθήκη μαθητή",
  "class.report": "Αναφορά",
  "class.newReport": "+ Νέα αναφορά",
  "class.defaultNewReportKind": "Προεπιλεγμένος τύπος νέων αναφορών",
  "class.defaultNewReportKindHint":
    "Τυπικό (τρία τρίμηνα) ή σύντομος κύκλος (μία περίοδος). Ισχύει με το + Νέα αναφορά· αποθηκεύστε μετά την αλλαγή.",
  "class.reportKindStandard": "Τυπικό (τρία τρίμηνα)",
  "class.reportKindShortCourse": "Σύντομος κύκλος (μία περίοδος)",
  "class.shortCourseReportLink": "Σύντομος κύκλος",
  "class.deletePupil": "Διαγραφή μαθητή",
  "class.editPupil": "Επεξεργασία",
  "class.savePupilEdits": "Αποθήκευση",
  "class.cancelPupilEdit": "Ακύρωση",
  "class.noPupils": "Κανένας μαθητής ακόμη — προσθέστε έναν παραπάνω.",
  "class.confirmYearChange":
    "Η αλλαγή σχολικού έτους αρχειοθετεί το τρέχον (όλες οι αναφορές), μετά τις αφαιρεί για νέο κύκλο. Οι μαθητές παραμένουν. Συνέχεια;",
  "class.confirmRemoveStudent": "Αφαίρεση {name} από αυτή την τάξη; Όλες οι αναφορές του διαγράφονται.",
  "class.activeDaysLabel": "Ημέρες διδασκαλίας",
  "class.activeDaysDisplay": "Ενεργές ημέρες (παρουσίες)",
  "class.printRegister": "Εκτύπωση παρουσιολογίου",
  "class.registerPreviewTitle": "Προεπισκόπηση παρουσιολογίου",
  "class.registerPreviewHint": "PDF κάτω· χρησιμοποιείτε Εκτύπωση για λήψη.",
  "class.printRegisterNeedDays": "Επιλέξτε πρώτα ημέρες στην τάξη στις ρυθμίσεις.",
  "class.printRegisterNeedStudents": "Προσθέστε μαθητές πριν την εκτύπωση.",
  "class.duplicatePupilWarning":
    "Προσοχή: το ίδιο όνομα υπάρχει ήδη σε: {locations}. Μπορείτε να προσθέσετε τον μαθητή αν ενδείκνυται.",
  "class.duplicatePupilThisClass": "αυτή η τάξη",
  "class.duplicatePupilUnnamedClass": "(τάξη χωρίς όνομα)",
  "weekday.mon": "Δευτέρα",
  "weekday.tue": "Τρίτη",
  "weekday.wed": "Τετάρτη",
  "weekday.thu": "Πέμπτη",
  "weekday.fri": "Παρασκευή",
  "weekday.sat": "Σάββατο",
  "weekday.sun": "Κυριακή",
};

const missing = keys.filter((k) => el[k] == null);
if (missing.length) {
  console.error("Missing Greek for keys:", missing);
  process.exit(1);
}

let body = "/** Greek strings mirroring `ES` overrides — merged over EN for locale `el`. */\nexport const EL_BODY: Record<string, string> = {\n";
for (const k of keys) {
  const v = el[k];
  body += `  ${JSON.stringify(k)}: ${JSON.stringify(v)},\n`;
}
body += "};\n";
const outPath = path.join(root, "src/lib/i18n/localeElBody.ts");
fs.writeFileSync(outPath, body);
console.log("Wrote", outPath, "keys", keys.length);
